### ISSUE TITLE
Professors should be able to impersonate students

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#166]
prof impersonation
  - [ ] UI to choose a student
  - [ ] profs can impersonate their students
  - anyone (not just admins) can stop impersonating

**Comment by blerner** [comment]
Just leaving a comment that this feature is less crucial right now, since we do have the ability for professors to retroactively grant accommodations to students and allow them to submit an exam much later, which is one of the main reasons professors might need to impersonate a student in Bottlenose.  It is definitely good to have, and shouldn't be too hard to implement (it's just a slightly looser authorization check), but is not urgently necessary.
