### ISSUE TITLE
Replace getters with has_many

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#180]
Replace collection getters that look like

```ruby
def proctors
  User.where(id: proctor_registrations.select(:user_id))
end
```

with `has_many through: ...` associations.

**Comment by blerner** [comment]
That's fine, just confirm that the `has_many through:` approach is similarly efficient of queries.

**Comment by blerner** [comment]
This won't work: `proctors_and_professors`, or `everyone`, or other combined queries, will bail out with an exception because `or` won't combine non-structurally-similar tables.  (There are distinct `JOIN`s that get in the way.)  Fortunately, the queries we currently have _do_ combine, and generate equally efficient query plans, so we wouldn't gain much by this.

Noting for the future: possibly https://github.com/MaxLap/activerecord_where_assoc might be of help.
