### ISSUE TITLE
Student name visible to graders

### ISSUE THREAD

**Issue by cjcodell1** [CodeGrade/hourglass#244]
I know the student's name is grayed out on the page listing the assignments I've graded, but when I click on a submission to re-claim a problem I can see the student's name at the top of the page. I took the screenshot too quickly but you can see the name appears in the browser tab too.

![bug](https://user-images.githubusercontent.com/26935146/100157555-bc988f00-2e78-11eb-9234-96fe258ecfe8.png)

**Comment by blerner** [comment]
Yes, it's a known issue.  It's hard to figure out exactly when to reveal the name or not: after all, you might need to regrade a particular person, eventually, and need to look them up by name.  The "censor bars" we currently have in the list of graded submissions is a compromise, since you can click on them to unmask the names.  We _should_ propagate those censor bars to these names...but this page is the same page that students themselves and profs can see when reviewing a student's submissions, and in those circumstances the name shouldn't be censored.
