### ISSUE TITLE
Editing a comment sets the last known value, not the new value

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/hourglass#398]
Potentially need to do
https://github.com/CodeGrade/hourglass/blob/25e932b8d7c30e26ebf41a1944cc5a8b60757b01/app/packs/components/workflows/grading/index.tsx#L262-L264
after
https://github.com/CodeGrade/hourglass/blob/25e932b8d7c30e26ebf41a1944cc5a8b60757b01/app/packs/components/workflows/grading/index.tsx#L247

**Comment by blerner** [comment]
I think this _might_ be slightly more tricky than just that fix, since we've already called `onBlur` in that handler.  I suspect this means that if we add a call to a second callback, one of them will get stale data (because we won't yet have had another render cycle to update all the stateful hooks).  It's worth trying, but I bet we'll have to update the signature of `onBlur` to potentially take in the final `pointStr` string.

**Comment by blerner** [comment]
What was the minimal repro scenario we needed, here?

**Comment by blerner** [comment]
Making a note of the repro steps:
1. Create a comment, and set its value to e.g. +5
2. Shift focus away from the comment editor.  A `mutateUpdate` will fire, and set the value to +5
3. Edit the comment again, and change the value to e.g. -7
4. Shift focus away from the comment editor.  A `mutateUpdate` will fire again, but set the value to +5 again, because the `doUpdate` function seems to be getting called before the `setValue` triggers React to update and rerender its hooks.

One potential solution is to use a `setCallback` to get the updated state value somehow.  Another "solution" is to use `setValue((newValue) => mutateUpdate(...newValue))`, which gets the updated state value even though React hasn't rerendered yet.

**Comment by blerner** [comment]
https://github.com/the-road-to-learn-react/use-state-with-callback/blob/master/src/index.js and https://www.robinwieruch.de/react-usestate-callback/ seem potentially useful.  But I think the fundamental issue here is, the `blur` event races with the react hooks.  Perhaps the right trick here is to use the same gimmick as https://github.com/CodeGrade/hourglass/blob/master/app/packs/components/workflows/grading/index.tsx#L426, and have the `onBlur` handler call `setNeedsSaving(true)`, and have a `useEffect(() => { if (needsSaving) { mutateUpdate(...); setNeedsSaving(false); }, [needsSaving])`, which _should_ delay the call to `mutateUpdate` until after all the react hooks have resolved.

**Comment by blerner** [comment]
Fixed by https://github.com/CodeGrade/hourglass/commit/7840e175ef9e02737fb04af617ab1d4c948028f6
